spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  jpa:
    hibernate:
      ddl-auto:
        none
  datasource:
    url:
      jdbc:mysql://localhost:3307/mydb
    username:
      bug_user
    password:
      ${MYSQL_PASSWORD}
    driver-class-name:
      com.mysql.cj.jdbc.Driver
management:
  endpoint:
    env:
      show-values: always